# This is a basic workflow to help you get started with Actions

name: Publish to test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # dependencies:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: npm install
  #     - uses: actions/cache@v1
  #       id: cache-dependencies
  #       with:
  #         path: '.'
  #         key: ${{ github.sha }}

  build:
    runs-on: ubuntu-latest
    # needs: dependencies
    steps:
      - uses: actions/cache@v1
        id: restore-dependencies
        with:
          path: '.'
          key: ${{ github.sha }}
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          pass: ${{ secrets.SERVER_PASS }}
          user: ${{ secrets.SERVER_USER }}
          command: |
            cd /home/klxhunter/klxhunter/devops/projects/test_cicd
            ls
            git status
            git checkout main
            git pull
