# This is a basic workflow to help you get started with Actions

name: Publish to test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # dependencies:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: npm install
  #     - uses: actions/cache@v1
  #       id: cache-dependencies
  #       with:
  #         path: '.'
  #         key: ${{ github.sha }}

  build:
    runs-on: ubuntu-latest
    # needs: dependencies
    steps:
      - uses: actions/cache@v1
        id: restore-dependencies
        with:
          path: '.'
          key: ${{ github.sha }}
      # - name: Build
      #   run: npm run build
      - name: Apt
        run: apt-get install sshpass -y
      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: 22
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          run: sshpass -p 'klxhunter' ssh klxhunter@valorwar.ml
