# This is a basic workflow to help you get started with Actions

name: Publish to production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_DEV }}
          pass: ${{ secrets.SERVER_PASS }}
          user: ${{ secrets.SERVER_USER }}
          command: |
            cd /home/klxhunter/klxhunter/devops/projects/test_cicd/manga-test
            git status
            git checkout main
            git pull
            docker run --rm -v $(pwd):/usr/src --workdir /usr/src --name node_dev_prem node:15.14.0-alpine3.13 npm run build
